// <auto-generated />
using AuMVC.Data;
using AuMVC.Data.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AuMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180303203611_3March")]
    partial class _3March
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuMVC.Data.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<string>("Code");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Item");

                    b.Property<string>("Note");

                    b.Property<int>("Priority");

                    b.Property<int>("SiteId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("AuMVC.Data.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<DateTime>("DateRaised");

                    b.Property<string>("IssueCode");

                    b.Property<string>("Item");

                    b.Property<string>("Note");

                    b.Property<int>("Priority");

                    b.Property<int>("SiteId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("AuMVC.Data.Models.ProgressStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovedBy");

                    b.Property<string>("CompletedBy");

                    b.Property<DateTime>("DateApproved");

                    b.Property<DateTime>("DateCompleted");

                    b.Property<DateTime>("DatePaid");

                    b.Property<int>("PaymentStatus");

                    b.Property<int>("SiteId");

                    b.Property<int>("Stage");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("ProgressStages");
                });

            modelBuilder.Entity("AuMVC.Data.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactNumber");

                    b.Property<DateTime>("ContractDate");

                    b.Property<double>("ContractValueExGST");

                    b.Property<double>("ContractValueIncGST");

                    b.Property<DateTime>("DOPCDate");

                    b.Property<string>("HomeOwner");

                    b.Property<string>("HouseType");

                    b.Property<string>("Note");

                    b.Property<int>("PreContactEOT");

                    b.Property<string>("SiteNumber")
                        .IsRequired();

                    b.Property<DateTime>("TwelveMonthMaintenance");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("AuMVC.Data.Models.Variation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Claimed");

                    b.Property<string>("Comment");

                    b.Property<int>("Contract");

                    b.Property<DateTime>("DateReleased");

                    b.Property<string>("Description");

                    b.Property<int>("EOT");

                    b.Property<string>("Location");

                    b.Property<bool>("Paid");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<double>("Price");

                    b.Property<int>("SiteId");

                    b.Property<int>("Status");

                    b.Property<string>("VariationCode");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Variations");
                });

            modelBuilder.Entity("AuMVC.Data.Models.Issue", b =>
                {
                    b.HasOne("AuMVC.Data.Models.Site", "Site")
                        .WithMany("Issues")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuMVC.Data.Models.Maintenance", b =>
                {
                    b.HasOne("AuMVC.Data.Models.Site", "Site")
                        .WithMany("Maintenances")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuMVC.Data.Models.ProgressStage", b =>
                {
                    b.HasOne("AuMVC.Data.Models.Site", "Site")
                        .WithMany("ProgressStages")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuMVC.Data.Models.Variation", b =>
                {
                    b.HasOne("AuMVC.Data.Models.Site", "Site")
                        .WithMany("Variations")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
